services:
  - type: web
    name: volunteerm
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --access-logfile - --error-logfile -

    envVars:
      - key: ENVIRONMENT
        value: production

      - key: SECRET_KEY
        sync: false

      - key: GOOGLE_CLIENT_ID
        sync: false

      # Ya la defines en Render como Internal Database URL string
      - key: DATABASE_URL
        sync: false

      # Coma-separado: "tuemail@dominio.com,otro@dominio.com"
      - key: ADMIN_EMAILS
        sync: false
